language: python
dist: focal
python:
- '3.8'
cache:
  directories:
  - ".cache"
before_install:
- set -e
- ". $HOME/.nvm/nvm.sh"
- nvm ls
- nvm ls-remote
- nvm install v16.13.2
- rm -rf node_modules
- npm install
- git checkout package.json package-lock.json
- git config pull.rebase false
- git fetch origin btse
- git branch btse origin/btse
- git checkout btse
- sudo -H pip install --upgrade setuptools
- sudo -H pip install --upgrade pip wheel requests pyopenssl
- sudo -H pip install --ignore-installed six
- sudo -H pip install --upgrade tox twine
- pip install --upgrade setuptools
- pip install --upgrade aiohttp requests cryptography pyopenssl
- composer install
- composer require --ignore-platform-reqs react/http:"^1.4.0" recoil/react:"1.0.2"
script:
- npm run test-base
- bash -c 'node run-tests btse --js' 2>&1
after_failure:
- dmesg | grep -i kill
after_script:
- cat ~/.npm/_logs/*-debug.log
